import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import Team from '../domain/interfaces/Team.interface';
import Stage from '../domain/Stage.enum';
import styles from '../styles/Home.module.css'
import teamsData from '../teams.json';
import { getTwoRivalsByStage } from '../utils/businessLogic';

const Home: NextPage = () => {
  const [ availableTeams, setAvailableTeams ] = useState<Team[]>(teamsData as Team[]);
  const [ currentMatch, setCurrentMatch ] = useState<Team[]>([]);
  const [ allRivalsPairing, setAllRivalsPairing ] = useState<Team[][]>([]);

  const updateAvailableTeams = (twoRivals: Team[]): void => {
    const newAvailableTeams = availableTeams
      .filter(team => team.id !== twoRivals[0].id && team.id !==twoRivals[1].id);
    setAvailableTeams(newAvailableTeams);
  } 
  
  const getNewTeamsMatching = () => {
    const twoRivals = getTwoRivalsByStage(availableTeams, Stage.ROUND_OF_16);
    setCurrentMatch(twoRivals);
    setAllRivalsPairing ([
      ...allRivalsPairing,
      twoRivals
    ]);
    updateAvailableTeams(twoRivals);
  }

  const renderTeamsInfo = (): JSX.Element[] | false => {
    return !!currentMatch.length && currentMatch.map(team => {
      return (
        <div>
          <h3>{team.name}</h3>
          <p>{team.country}</p>
          <p>{team.group}</p>
          <p>{team.position}</p>
        </div>
      )
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Champions Draw</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Champions Draw
        </h1>
        <h2>TEAM MATCHING:</h2>
        {!!allRivalsPairing.length
          ? allRivalsPairing.map(rivals => {
          return <p>{rivals[0].name} VS {rivals[1].name}</p>
        })
          : <p>The draw has not started yet!</p>}
        <div className={styles.teams}>
          {renderTeamsInfo()}
        </div>        
        <button
          onClick={getNewTeamsMatching}
          disabled={availableTeams.length === 0 && currentMatch.length > 0}>
            {!currentMatch.length ? 'Start the draw' : 'New Draw!'}
        </button>
      </main>
    </div>
  )
}

export default Home
