import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import teamsData from '../teams.json';
import { getTwoRandomTeams } from '../utils/businessLogic';

const Home: NextPage = () => {
  const teams = getTwoRandomTeams(teamsData);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Champions Draw
        </h1>
        <div className={styles.teams}>
          <div>
            <h3>{teams[0].name}</h3>
            <p>{teams[0].country}</p>
            <p>{teams[0].group}</p>
          </div>
          <div>
            <h3>{teams[1].name}</h3>
            <p>{teams[1].country}</p>
            <p>{teams[1].group}</p>
          </div>

        </div>

        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
